name: AZD deployment test
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true

    - name: Install azd
      uses: Azure/setup-azd@v1.0.0

    - name: Deploy Infrastructure
      run: |
        azd auth login
        az deployment sub create \
          --location $(jq -r '.parameters.location.value' main.bicepparam) \
          --template-file main.bicep \
          --parameters @main.bicepparam